name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_DEFAULT_REGION: us-west-2

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build Docker image
        working-directory: realtime-chat-app
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/realtime-chat-app
          TAG=${GITHUB_REF##*/}
          docker build -t $IMAGE:$TAG .

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/realtime-chat-app
          TAG=${GITHUB_REF##*/}
          docker push $IMAGE:$TAG

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Apply
        working-directory: infrastructure
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="project_name=realtime-chat-app" \
            -var="docker_image=${{ secrets.DOCKER_USERNAME }}/realtime-chat-app" \
            -var="docker_tag=${GITHUB_REF##*/}"

      - name: Show application URL
        working-directory: infrastructure
        run: terraform output public_dns

      - name: Get EC2 public DNS
        id: tf-output
        working-directory: infrastructure
        run: |
          echo "APP_URL=http://$(terraform output -raw public_dns)" >> $GITHUB_ENV

      - name: Wait for application to start
        run: sleep 20

      - name: Smoke test application
        run: |
          echo "Testing $APP_URL"
          curl --fail $APP_URL
